"""
The written record of everything Locus knows about one pull request.

The PR comment is deliberately short -- it is read in a diff view, next to the
code, by someone deciding whether to approve. This is the opposite document:
the senior dev and the testing team are asked to trust a verdict produced by a
pipeline they did not watch, and "trust it" is only reasonable if they can read
what it actually did.

So this renders the whole run, not a summary of it: the requirement as stated
in the ticket and argued in Slack, the diff, both analysis passes, what moved
since last round, every review round with the reviewer's own words, every
message sent and received in both loops, and the searches that found nothing.
The last of those matters more than it looks -- "Slack was searched and nothing
matched" and "Slack was never searched" produce identical silence everywhere
else, and only one of them means the requirement context is missing.

Nothing here is generated by a model. Every line is a record of something that
happened, so the document cannot be wrong in the way a summary can.

Ordering is chronological within each section rather than by severity: this is
the story of a change, and someone reading it a month later is reconstructing
what happened and when, not triaging.
"""

import logging
from datetime import UTC, datetime
from zoneinfo import ZoneInfo

from app import models, schemas
from app.services.datetimes import DEFAULT_TIMEZONE

logger = logging.getLogger(__name__)

# Enough of a message to carry its meaning into the record. Past this a single
# pasted stack trace crowds out everything around it.
MAX_BODY_CHARS = 2000

_DIRECTION_LABEL = {
    "searched": "Searched",
    "sent": "Sent",
    "received": "Received",
}

_LOOP_LABEL = {
    "context": "Context gathering",
    "review": "Senior dev review",
    "qa": "Testing team",
}


def _local(stamp: datetime | None, timezone_name: str | None = None) -> str:
    """
    A timestamp as a human in the team's timezone reads it.

    Rows written by SQLite carry no offset; they are UTC instants either way,
    so an unlabelled one is read as UTC rather than as the server's local time.
    Resolving against the server would drift the whole document by hours with
    nothing on the page to reveal it.
    """
    if stamp is None:
        return "unknown time"

    if stamp.tzinfo is None:
        stamp = stamp.replace(tzinfo=UTC)

    zone = ZoneInfo(timezone_name or DEFAULT_TIMEZONE)
    return stamp.astimezone(zone).strftime("%d %b %Y, %H:%M %Z")


def _clip(text: str | None, limit: int = MAX_BODY_CHARS) -> str:
    """Trim a body, saying so rather than ending mid-sentence in silence."""
    if not text:
        return ""
    text = text.strip()
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + f"\n… [trimmed, {len(text)} chars total]"


def _quote(text: str) -> str:
    """Indent a body so it cannot be mistaken for the document's own prose."""
    return "\n".join(f"    {line}" for line in text.splitlines())


def _event_lines(
    event: models.CommunicationEvent,
    timezone_name: str | None,
) -> list[str]:
    """One communication event, rendered with everything recorded about it."""
    direction = _DIRECTION_LABEL.get(event.direction, event.direction)
    header = f"{_local(event.created_at, timezone_name)} — {direction} · {event.channel}"

    if getattr(event, "inherited", False):
        # Discussion cached under the work item by a sibling PR. The analysis
        # was given it, so omitting it would understate the context used --
        # but showing it unmarked would read as discussion about this PR.
        header += "  [inherited from the work item]"

    lines = [header]

    detail = []
    if event.participant:
        detail.append(f"who: {event.participant}")
    if event.target:
        detail.append(f"where: {event.target}")
    if event.outcome:
        detail.append(f"outcome: {event.outcome}")
    if not event.succeeded:
        # The one thing in this table that must never be quiet: a message
        # nobody received looks identical to one nobody replied to.
        detail.append("DELIVERY FAILED")
    if detail:
        lines.append("  " + " · ".join(detail))

    if event.query:
        # Kept even when nothing matched: a search that found nothing is
        # otherwise indistinguishable from one that never ran.
        lines.append(f'  query: "{event.query}"')
    if event.subject:
        lines.append(f"  subject: {event.subject}")
    if event.permalink:
        lines.append(f"  link: {event.permalink}")

    body = _clip(event.body)
    if body:
        lines.append("")
        lines.append(_quote(body))

    lines.append("")
    return lines


def render(
    result: schemas.PRAnalysisResult,
    *,
    events: list[models.CommunicationEvent] | None = None,
    review: models.PRReview | None = None,
    timezone_name: str | None = None,
    generated_at: datetime | None = None,
) -> str:
    """
    Render the complete report for one pull request.

    Args:
        result: The current run's analysis. Passed in rather than re-read: a
            stored one would describe an earlier round's code.
        events: The communication timeline, oldest first.
        review: The review row, for the round-by-round history GitHub does not
            keep.

    Returns:
        Plain text. Google Docs stores it as text rather than parsing Markdown,
        so the structure is carried by spacing and rules instead of by markup
        that would render as literal `##` on the page.
    """
    ctx = result.context
    out: list[str] = []

    def rule(title: str) -> None:
        out.extend(["", "=" * 72, title.upper(), "=" * 72, ""])

    # --- Header ---------------------------------------------------------
    out.append(f"{ctx.repo}#{ctx.pr_number} — {ctx.title}")
    out.append("")
    out.append(f"Author:      {ctx.author}")
    out.append(f"Pull request: {ctx.url}")
    if ctx.branch:
        out.append(f"Branch:      {ctx.branch}")
    out.append(
        f"Changes:     {ctx.files_changed} file(s), "
        f"+{ctx.additions}/-{ctx.deletions}"
    )
    out.append(
        f"Report written: {_local(generated_at or datetime.now(UTC), timezone_name)}"
    )
    out.append("")
    out.append(
        "Everything below is a record of what happened, not a summary of it. "
        "No part of this document is written by a model."
    )

    # --- The requirement ------------------------------------------------
    rule("What this change was meant to do")

    if ctx.tickets:
        for ticket in ctx.tickets:
            out.append(f"{ticket.key} — {ticket.summary or 'no summary'}")
            meta = [d for d in (ticket.status, ticket.assignee) if d]
            if meta:
                out.append(f"  {' · '.join(meta)}")
            if ticket.url:
                out.append(f"  {ticket.url}")
            out.append("")
    elif ctx.ticket_keys:
        out.append(
            "Referenced but not resolvable: " + ", ".join(ctx.ticket_keys)
        )
        out.append("")
    else:
        out.append("No ticket was referenced or found.")
        out.append("")

    if ctx.linked_issues:
        out.append("Linked issues")
        for issue in ctx.linked_issues:
            out.append(
                f"  #{issue.number} ({issue.relation}, {issue.state}) — "
                f"{issue.title}"
            )
        out.append("")

    if ctx.documents:
        out.append("Context documents read on this run")
        for doc in ctx.documents:
            out.append(f"  {doc.title or 'untitled'} — {doc.url or ''}")
            excerpt = _clip(doc.excerpt, 600)
            if excerpt:
                out.append(_quote(excerpt))
        out.append("")

    # --- Discussion -----------------------------------------------------
    rule("Discussion this change was based on")

    if ctx.slack_threads:
        for thread in ctx.slack_threads:
            who = ", ".join(thread.participants) if thread.participants else "unknown"
            out.append(f"#{thread.channel} · {who}")
            if thread.message_count:
                out.append(f"  {thread.message_count} message(s)")
            if thread.permalink:
                out.append(f"  {thread.permalink}")
            body = _clip(thread.summary)
            if body:
                out.append("")
                out.append(_quote(body))
            out.append("")
    else:
        out.append(
            "No Slack discussion was matched to this work item. See the "
            "activity log below for the searches that ran."
        )
        out.append("")

    # --- Security -------------------------------------------------------
    rule("Security scan")

    if result.confirmed_findings:
        out.append(
            "Confirmed — deterministic rule matches from Semgrep or Gitleaks."
        )
        out.append("")
        for finding in result.confirmed_findings:
            out.append(f"  [{finding.severity.value}] {finding.title}")
            out.append(f"    {finding.file_path}:{finding.line or '?'}")
            if finding.description:
                out.append(f"    {finding.description}")
            out.append("")
    else:
        out.append("No confirmed findings.")
        out.append("")

    if result.unverified_findings:
        out.append(
            "Unverified — reported by the model and not confirmed by a "
            "scanner. Treated as a lead, never as a fact."
        )
        out.append("")
        for finding in result.unverified_findings:
            out.append(f"  [{finding.severity.value}] {finding.title}")
            out.append(f"    {finding.file_path}:{finding.line or '?'}")
            if finding.description:
                out.append(f"    {finding.description}")
            out.append("")

    # --- Code review ----------------------------------------------------
    rule("Code review")
    out.append(
        "A judgement about whether the change is correct and does what the "
        "team asked. Priorities are the reviewer's call, not a CVSS rating."
    )
    out.append("")

    if result.review_findings:
        for finding in result.review_findings:
            out.append(
                f"  {finding.priority.value.upper()} "
                f"({finding.category or 'general'}) — {finding.title}"
            )
            if finding.file_path:
                out.append(
                    f"    {finding.file_path}:{finding.line or '?'}"
                )
            if finding.description:
                out.append(f"    {finding.description}")
            if getattr(finding, "suggested_fix", None):
                out.append("    Suggested replacement:")
                out.append(_quote(_clip(finding.suggested_fix, 800)))
            out.append("")
    else:
        out.append("  Nothing flagged.")
        out.append("")

    # --- Movement -------------------------------------------------------
    if result.delta is not None:
        rule("What moved since the previous round")
        delta = result.delta
        out.append(f"No longer reported: {len(delta.resolved)}")
        for title in delta.resolved:
            out.append(f"  - {title}")
        out.append(f"Still open: {len(delta.persisting)}")
        for title in delta.persisting:
            out.append(f"  - {title}")
        out.append(f"New this round: {len(delta.introduced)}")
        for title in delta.introduced:
            out.append(f"  - {title}")
        out.append("")
        out.append(
            'Resolved is worded "no longer reported" deliberately: deleting a '
            "file resolves a finding too, and this knows what it stopped "
            "seeing, not what anyone did about it."
        )
        out.append("")

    # --- Review history -------------------------------------------------
    rule("Review history")

    if review is not None and review.rounds:
        out.append(
            f"Current state: {review.state} · round {review.round_number}"
        )
        if review.last_reviewer:
            out.append(f"Last reviewer: {review.last_reviewer}")
        out.append("")

        for round_ in sorted(review.rounds, key=lambda r: r.id):
            out.append(
                f"Round {round_.round_number} — {round_.outcome} "
                f"({round_.reviewer or 'no reviewer recorded'}) "
                f"· {_local(round_.created_at, timezone_name)}"
            )
            if round_.head_sha:
                out.append(f"  commit: {round_.head_sha[:12]}")
            body = _clip(round_.body)
            if body:
                out.append("")
                out.append(_quote(body))
            out.append("")
    else:
        out.append("No review has been submitted on this pull request yet.")
        out.append("")

    # --- Activity log ---------------------------------------------------
    rule("Everything Locus searched, sent and received")
    out.append(
        "The full record for this pull request, oldest first. Searches that "
        "matched nothing are included: a search that found nothing and a "
        "search that never ran look identical everywhere else."
    )
    out.append("")

    if events:
        by_loop: dict[str, list[models.CommunicationEvent]] = {}
        for event in events:
            by_loop.setdefault(event.loop, []).append(event)

        for loop in ("context", "review", "qa"):
            loop_events = by_loop.get(loop)
            if not loop_events:
                continue
            out.append("-" * 72)
            out.append(_LOOP_LABEL.get(loop, loop))
            out.append("-" * 72)
            out.append("")
            for event in sorted(
                loop_events, key=lambda e: (e.created_at or datetime.min, e.id)
            ):
                out.extend(_event_lines(event, timezone_name))

        # A loop this module does not know about must still appear; silently
        # dropping rows would make the record incomplete without saying so.
        for loop, loop_events in by_loop.items():
            if loop in ("context", "review", "qa"):
                continue
            out.append("-" * 72)
            out.append(loop)
            out.append("-" * 72)
            out.append("")
            for event in loop_events:
                out.extend(_event_lines(event, timezone_name))
    else:
        out.append("Nothing recorded.")
        out.append("")

    # --- Pipeline -------------------------------------------------------
    rule("Pipeline steps")
    out.append(
        "Each step this run took, including the ones that were skipped or "
        "failed. A step that did not run is the usual reason a report is "
        "missing something."
    )
    out.append("")

    for stage in result.stages:
        line = f"  [{stage.state.value}] {stage.label}"
        if stage.detail:
            line += f" — {stage.detail}"
        out.append(line)
    out.append("")

    if result.errors:
        out.append("Errors recorded during this run")
        for error in result.errors:
            out.append(f"  - {error}")
        out.append("")

    return "\n".join(out)
